import "./globals.css";
import ToastProvider from "./ToastProvider";
import ReduxProvider from "./reduxProvider";
import No_Internet from "./_components/_ui/No_Internet";

export const metadata = {
  title: "Zwiggy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <ToastProvider>
        <No_Internet/>
        <html lang="en">
          
          <body>{children}</body>
        </html>
      </ToastProvider>
    </ReduxProvider>
  );
}
