import "./globals.css";
import ToastProvider from "./_wrappers/ToastProvider";
import ReduxProvider from "./_wrappers/reduxProvider";
import No_Internet from "./_wrappers/No_Internet";
import AuthProviderWrapper from "./_wrappers/AuthProvider";
import { Nunito } from "next/font/google";

export const metadata = {
  title: "Swiggy-A Food App",
  description: "Generated by create next app",
};

const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });


  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body  
        className={nunito.className}
        >
          <ReduxProvider>
            <ToastProvider/>
              <No_Internet/>
              <AuthProviderWrapper>
              {children}
              </AuthProviderWrapper>
          </ReduxProvider>
        </body>
      </html>
    );
  }
